import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
    Box,
    Button,
    ButtonGroup,
    Input,
    Stack,
    Wrap,
    WrapItem,
} from "@chakra-ui/react";
import { trpc } from "../utils/trpc";
import { ChangeEvent, useState } from "react";

const Home: NextPage = () => {
    const [value, setValue] = useState("");
    const commentMutation = trpc.useMutation(["example.add-comment"]);

    const submitComment = () => {
        commentMutation.mutate({ comment: value });
    };

    const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
        setValue(event.target.value);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Stack direction="column">
                    <Box
                        display="flex"
                        alignItems="center"
                        justifyContent="center"
                        width="100%"
                        py={12}
                        bgImage="url('https://bit.ly/2Z4KKcF')"
                        bgPosition="center"
                        bgRepeat="no-repeat"
                        mb={2}
                    >
                        <ButtonGroup gap="4">
                            <Button colorScheme="whiteAlpha">WhiteAlpha</Button>
                            <Button colorScheme="blackAlpha">BlackAlpha</Button>
                        </ButtonGroup>
                    </Box>

                    <Wrap spacing={4}>
                        <WrapItem>
                            <Button colorScheme="gray">Gray</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="red">Red</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="orange">Orange</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="yellow">Yellow</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="green">Green</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="teal">Teal</Button>
                        </WrapItem>
                    </Wrap>
                </Stack>

                <Input
                    value={value}
                    onChange={handleChange}
                    placeholder="Here is a sample placeholder"
                    size="lg"
                />
                <Button colorScheme="green" onClick={submitComment}>
                    Green
                </Button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
