import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, Button, ButtonGroup, Stack, Wrap, WrapItem } from "@chakra-ui/react";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{" "}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>
                <Stack direction="column">
                    <Box
                        display="flex"
                        alignItems="center"
                        justifyContent="center"
                        width="100%"
                        py={12}
                        bgImage="url('https://bit.ly/2Z4KKcF')"
                        bgPosition="center"
                        bgRepeat="no-repeat"
                        mb={2}
                    >
                        <ButtonGroup gap="4">
                            <Button colorScheme="whiteAlpha">WhiteAlpha</Button>
                            <Button colorScheme="blackAlpha">BlackAlpha</Button>
                        </ButtonGroup>
                    </Box>

                    <Wrap spacing={4}>
                        <WrapItem>
                            <Button colorScheme="gray">Gray</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="red">Red</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="orange">Orange</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="yellow">Yellow</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="green">Green</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="teal">Teal</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="blue">Blue</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="cyan">Cyan</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="purple">Purple</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="pink">Pink</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="linkedin">Linkedin</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="facebook">Facebook</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="messenger">Messenger</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="whatsapp">Whatsapp</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="twitter">Twitter</Button>
                        </WrapItem>
                        <WrapItem>
                            <Button colorScheme="telegram">Telegram</Button>
                        </WrapItem>
                    </Wrap>
                </Stack>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
